# Power Transformer

Q. Explain transformer.
ANS. It is techinque of conversion of the skew or raw data in normal distribution form.     

Q. What is power transformer?
ANS. Power transformer is the techinque which convert our raw or skew data in normal distribution form.

Q. What are the different methods used for power transformer?
ANS. 1. Function Transformer(log transformer,square transformer,square root transformer)
     2. Power transformer(box-cox,Yeo-johnson)
     3. Quantile transformation

Q. Explain box-cox transformer.
ANS. It works over only positive data
-> IT tries to normalize data

Q. Explain yeo-johnson transformer.
ANS. It works on the same idea as box-cox but it works over both positive as well as negative data.

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats  # It is used for drawing the QQ plot

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score # it split your data into k times then run your model k times

# Working of the cross val score
Fold 1: [TEST] [train] [train] [train] [train]
Fold 2: [train] [TEST] [train] [train] [train]
Fold 3: [train] [train] [TEST] [train] [train]
Fold 4: [train] [train] [train] [TEST] [train]
Fold 5: [train] [train] [train] [train] [TEST]

Q. Explain LinearRegression.
ANS. It is model which use best fit line to predict the value for the new data.    

Q. Explain r2_score.
ANS. The dumbest thing you can do is just predict the mean every time — which is 200 here. No matter what house, you say "200 lakhs."
That's called the baseline model.
What R² actually measures
R² tells you — how much better is my model compared to that dumb baseline?
R² = 1 → your model predicts perfectly, zero error
R² = 0 → your model is exactly as good as just predicting the mean every time
R² = 0.85 → your model explains 85% of the variation in y. The remaining 15% it couldn't capture
R² < 0 → your model is actually worse than the dumb baseline. Something has gone seriously wrong

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [5]:
# importing PowerTransformer
from sklearn.preprocessing import PowerTransformer # this contains both box-cox as well as yeo-johnson

In [7]:
data = pd.read_csv('../../datasets/concrete_data.csv')

In [8]:
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [9]:
data.shape

(1030, 9)

In [10]:
data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age                 1030 non-null   int64
 8   Strength            1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [13]:
# This is used for analysing all the hidden values of the data
data.describe()
#Note -> box-cox transformer their  should be only positive values

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [14]:
data.head(3)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27

In [20]:
x = data.drop(columns=['Strength'])
y = data.iloc[:,8:9]

In [21]:
x.head(3)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270

In [22]:
y.head(3)

   Strength
0     79.99
1     61.89
2     40.27

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
# contnue after 9 minutes