### Training model using pipeline

In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [20]:
data = pd.read_csv('../datasets/titanic2.csv')

In [21]:
data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [22]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [23]:
# Removing unwanted columns
data.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [24]:
data.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0         0       3    male  34.5      0      0  7.8292        Q
1         1       3  female  47.0      1      0  7.0000        S
2         0       2    male  62.0      0      0  9.6875        Q

In [28]:
#step 1 : spliting data 
x_train,x_test,y_train,y_test = train_test_split(data.drop(columns=['Survived']),data['Survived'],test_size=0.3,random_state=42)

In [29]:
x_train.shape[0]

292

In [30]:
x_train.shape[1]

7

In [31]:
y_train.shape[0]

292

In [33]:
y_test.shape[0]

126

In [34]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
118       1    male  36.0      0      0   75.2417        C
271       3    male   NaN      0      0    7.7500        Q
114       1  female  63.0      1      0  221.7792        S
311       3    male  22.0      0      0    7.2250        C
131       1    male  53.0      0      0   28.5000        C

In [38]:
# It will return the random data 
y_train.sample()

344    0
Name: Survived, dtype: int64

### Mentoss jindaghi applying transformer